sonar.projectKey=aguilar-arce
sonar.projectName=Aguilar Arce
sonar.sources=app,routes,database,resources/views,resources/js,resources/css
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**
sonar.php.binaries=app
sonar.php.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
